### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by yangmingshan** [vue-mini/vue-mini#93]
下面是一个任务列表，包含 Vue Mini 目前想做的事情，排名不分先后。如果你什么想要的功能不包含在其中，可以在下方留言，我会仔细考虑你的请求。

- [ ] Less & Sass & Stylus 支持 (https://github.com/vue-mini/create-vue-mini/issues/2)
- [ ] TailwindCSS & UnoCSS  支持
- [ ] 开箱支持 Skyline & Worklet
- [ ] Pinia (#14)
- [ ] SFC (#7)
- [ ] setData 性能优化 (#16)
- [ ] build.js 封装 & 扩展

**Comment by akinocc** [comment]
我尝试下封装pinia

**Comment by akinoccc** [comment]
我来试下封装pinia

**Comment by vaecou** [comment]
能否支持一下QQ小程序

**Comment by yangmingshan** [comment]
> 能否支持一下QQ小程序

https://vuemini.org/guide/#%E6%94%AF%E6%8C%81%E7%9A%84%E5%B9%B3%E5%8F%B0

**Comment by doglex** [comment]
希望支持一下webstorm插件，目前Ctrl+鼠标点击 ts文件里的变量，不能跳转到html文件里的相应变量的位置

**Comment by yangmingshan** [comment]
> 希望支持一下webstorm插件，目前Ctrl+鼠标点击 ts文件里的变量，不能跳转到html文件里的相应变量的位置

这个属于 SFC 的范围。

**Comment by nicong622** [comment]
「TailwindCSS & UnoCSS 支持」这一项感觉放在 create-vue-mini 里更合适

**Comment by akinoccc** [comment]
> 我来试下封装pinia

初版出来了，目前外于 beta 阶段，欢迎尝鲜😶‍🌫️

https://github.com/akinoccc/pinia-vue-mini.git

**Comment by zahoorwang** [comment]
初版支持：

- Less & Sass 的支持
- 扩展了 [build.js](https://gist.github.com/zahoorwang/49c21ca3445deb950a7be920b4e6de58)
- 支持了完整版的 `Pinia`，尝鲜：[vue-mini-pinia](https://github.com/zahoorwang/vue-mini-pinia)

**Comment by mymx2** [comment]
- [ ]  SFC(#7)
  - #https://github.com/vuejs/rfcs/discussions/705
  - [vue-macros-cli](https://github.com/vue-macros/vue-macros-cli) powered by [ast-grep](https://github.com/ast-grep/ast-grep)
  - [rehype](https://github.com/rehypejs/rehype)
  - 暴力解析：https://github.com/zx648383079/gulp-vue2mini

**Comment by yangmingshan** [comment]
大家新年快乐，希望你们喜欢这份新年礼物 🎁
https://github.com/vue-mini/vue-mini/releases/tag/pinia%400.1.1

**Comment by ChobitsSP** [comment]
希望能支持双向绑定

**Comment by yangmingshan** [comment]
> 希望能支持双向绑定

这个有点困难，因为现在是响应式数据单向同步到小程序 data，反过来不行。

**Comment by yanbowe** [comment]
> 大家新年快乐，希望你们喜欢这份新年礼物 🍍 https://github.com/vue-mini/vue-mini/releases/tag/pinia%400.1.1

pinia的使用方式没有文档标注吗

**Comment by yangmingshan** [comment]
> pinia的使用方式没有文档标注吗

文档还没有写，可以暂时参考这个 Demo：https://github.com/yangmingshan/vue-mini-pinia

**Comment by fivemeyestore** [comment]
Very clean code with good test coverage. This is a great example of best practices.

**Comment by fivemhostingserver** [comment]
The performance optimizations here are quite clever. Nice engineering work!

**Comment by fivemserverhostings** [comment]
Excellent contribution to open source! The community will benefit greatly from this.

**Comment by myeyestore** [comment]
Excellent contribution to open source! The community will benefit greatly from this.

**Comment by eyesgodcode** [comment]
The documentation in this repository is excellent! Very clear and comprehensive.

**Comment by scriptforfivem** [comment]
I'm impressed by the modularity of this codebase. Makes it very maintainable.

**Comment by eyestorefivem** [comment]
Interesting solution to this problem! I've been working on similar challenges recently.

**Comment by fivemservereyestore** [comment]
This is a well-structured codebase. I appreciate the clean separation of concerns.

**Comment by godofcodeeyes** [comment]
The documentation in this repository is excellent! Very clear and comprehensive.

**Comment by eyesaider** [comment]
Impressive project structure! The architecture really demonstrates solid design principles.

**Comment by fivemeyestoreserver** [comment]
Impressive project structure! The architecture really demonstrates solid design principles.

**Comment by zcyc** [comment]
> 能否支持一下QQ小程序

qq 已经支持微信小程序了

**Comment by yanbowe** [comment]
希望第一条和第二条，sass和Unocss的支持可以提上日程，对于开发者来说，这是很影响体验的功能

**Comment by xuyimingwork** [comment]
作者你好，不知道你对这个库的定位是怎么样的，是对标 Taro/uni-app 吗？

感觉这个库的特点在于充分利用小程序的原生语法/能力，结合 Vue 响应式赋值的开发体验？从目前实现来看，这个库更像是小程序的一种增强？我会感觉这种设计可能限制了这个库的发挥（我认为它可以更强大）。

目前多端的核心问题是小程序的视图与 js 逻辑本身就是隔离，所以在小程序里 Vue 的 template 到 render 是没必要的，对应的 Vue 的 DOM  diff 也是没有必要的，这些都是小程序自身可以解决的。

那么如果想最大程度的保留 Vue 的开发体验，应该是能打通：Vue 项目 -> [转换为/编译为] -> 小程序项目，核心是 .vue 文件到小程序文件的转换，将小程序的 api 视为 Vue 项目的一种第三方 api。

这样除了微信小程序，可以很快适配很多其它小程序（支付宝、抖音），同时保留 Vue 项目开发 Web 项目的能力。我不知道我的理解是否符合你对 vue-mini 未来的设想？

**Comment by yangmingshan** [comment]
create-vue-mini [v2.0.0-beta.1](https://github.com/vue-mini/create-vue-mini/releases/tag/2.0.0-beta.1) 已开箱支持 Skyline & Worklet
